# Generated by Django 6.0.7 on 2026-07-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50)),
                ('kontrollziel', models.CharField(blank=True, max_length=255)),
                ('kontrollbeschreibung', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='ArbeitspapierSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_activities', models.TextField(blank=True)),
                ('kontrollergebnis_raw', models.TextField(blank=True)),
                ('no_deviation', models.BooleanField(default=False)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='controls.control')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField(blank=True)),
                ('audit_type', models.CharField(choices=[('soc2', 'SOC 2'), ('ps951', 'PS 951'), ('isae3402', 'ISAE 3402')], default='soc2', max_length=20)),
                ('report_kind', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], default='type1', max_length=10)),
                ('report_date', models.DateField()),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='controls.project'),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('project', 'control_id')},
        ),
    ]
