# Generated by Django 6.0.7 on 2026-07-18 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbeitspapiersubmission',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='arbeitspapiersubmission',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbeitspapiersubmission',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbeitspapiersubmission',
            name='validation_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='audit_type',
            field=models.CharField(choices=[('soc2', 'SOC 2'), ('ps951', 'PS 951'), ('ps3000', 'PS 3000')], default='soc2', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional, e.g. "Period 1"', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_periods', to='controls.project')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Used in templates as {{ key }}', max_length=100, unique=True)),
                ('section', models.CharField(choices=[('project_info', 'Project info'), ('audit_period', 'Audit period'), ('controls', 'Control table'), ('custom', 'Custom / other')], default='custom', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_custom', models.BooleanField(default=False, help_text='True for user-added placeholders (stored in Project.extra_fields)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('audit_type', models.CharField(choices=[('soc2', 'SOC 2'), ('ps951', 'PS 951'), ('ps3000', 'PS 3000')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], max_length=2)),
                ('file', models.FileField(upload_to='report_templates/')),
                ('preview_pdf', models.FileField(blank=True, null=True, upload_to='report_templates/previews/')),
                ('is_active', models.BooleanField(default=True, help_text='Used when generating reports for this audit type/language')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
