# Generated by Django 6.0.7 on 2026-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_alter_arbeitspapiersubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='control',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='arbeitspapiersubmission',
            name='geprueft_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbeitspapiersubmission',
            name='geprueft_von',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='examination_date',
            field=models.DateField(blank=True, help_text='Type 1 only: date of examination', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='audit_type',
            field=models.CharField(choices=[('soc2', 'SOC 2'), ('ps951', 'PS 951'), ('ps3000', 'PS 3000'), ('isae3402', 'ISAE 3402')], default='soc2', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='audit_type',
            field=models.CharField(choices=[('soc2', 'SOC 2'), ('ps951', 'PS 951'), ('ps3000', 'PS 3000'), ('isae3402', 'ISAE 3402')], max_length=20),
        ),
    ]
