# Generated by Django 6.0.7 on 2026-07-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_control_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('import', 'Working paper imported'), ('edit', 'Manually edited in app')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='controls.control')),
            ],
            options={
                'verbose_name_plural': 'Change log entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
