# Generated by Django 6.0.7 on 2026-07-18 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_changelogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], max_length=2)),
                ('phrase', models.CharField(help_text="Literal text to search for, or a regex pattern if 'Is pattern' is checked", max_length=300)),
                ('is_pattern', models.BooleanField(default=False, help_text="Treat 'phrase' as a regex pattern (case-insensitive) instead of a plain substring -- use for phrases with variable text in the middle")),
                ('description', models.CharField(blank=True, help_text='Optional human-readable label shown in validation messages instead of the raw pattern', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['language', 'order', 'id'],
            },
        ),
    ]
