# Generated by Django 6.0.7 on 2026-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_standardphrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardphrase',
            options={'ordering': ['language', 'id']},
        ),
        migrations.RemoveField(
            model_name='standardphrase',
            name='is_pattern',
        ),
        migrations.RemoveField(
            model_name='standardphrase',
            name='order',
        ),
        migrations.AlterField(
            model_name='standardphrase',
            name='phrase',
            field=models.CharField(help_text="Matched as a case-insensitive regex, e.g. 'review of .* with regard to the following aspects:'", max_length=300),
        ),
    ]
