# Generated by Django 6.0.7 on 2026-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_alter_standardphrase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardphrase',
            name='description',
        ),
        migrations.AlterField(
            model_name='standardphrase',
            name='phrase',
            field=models.CharField(help_text="Matched as a case-insensitive regex, e.g. 'Review of .* with regard to the following aspects:'", max_length=300),
        ),
    ]
