# Generated by Django 6.0.7 on 2026-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_remove_standardphrase_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='event_type',
            field=models.CharField(choices=[('import', 'Working paper imported'), ('edit', 'Manually edited in app'), ('delete', 'Submission deleted')], max_length=10),
        ),
    ]
