# Generated by Django 6.0.7 on 2026-07-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_alter_changelogentry_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='reviewed_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='reviewed_ok_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='reviewed_ok_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_reviewed_ok', to=settings.AUTH_USER_MODEL),
        ),
    ]
