# Generated by Django 6.0.7 on 2026-07-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_control_reviewed_ok_control_reviewed_ok_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='reference_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('criteria', models.CharField(blank=True, max_length=255)),
                ('control_id', models.CharField(blank=True, max_length=50)),
                ('kontrollbeschreibung', models.TextField(blank=True)),
                ('test_performed', models.TextField(blank=True)),
                ('result_text', models.TextField(blank=True)),
                ('reference_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='controls.referencereport')),
            ],
            options={
                'ordering': ['reference_report', 'order'],
            },
        ),
    ]
