# Generated by Django 6.0.7 on 2026-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_referencereport_referencereportentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencereport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reference_reports/'),
        ),
    ]
