# Generated by Django 6.0.7 on 2026-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_referencereport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='date_format',
            field=models.CharField(blank=True, choices=[('en_ordinal', 'English — e.g. 8th October 2025'), ('de_ordinal', 'German — e.g. 1. Januar 2025')], default='en_ordinal', max_length=10),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date')], default='text', help_text='Date fields get a date picker on the project form, and are formatted per date_format when a report is generated', max_length=10),
        ),
    ]
