# Generated by Django 6.0.7 on 2026-07-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_placeholder_date_format_placeholder_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='import_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
