# Generated by Django 6.0.7 on 2026-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0013_control_import_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_subservice_org',
            field=models.BooleanField(default=False),
        ),
    ]
